### ISSUE TITLE
IsUni4 throws an exception

### ISSUE THREAD

**Issue by Deantwo** [Deantwo/HazeronAdviser#26]
See the end of this message for details on invoking 
    just-in-time (JIT) debugging instead of this dialog box.
    
    ************** Exception Text **************
    System.IndexOutOfRangeException: Index was outside the bounds of the array.
       at HazeronAdviser.HMail.IsUni4(Byte[] mailBytes)
       at HazeronAdviser.Main.btnScan_Click(Object sender, EventArgs e)
       at System.Windows.Forms.Control.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ButtonBase.WndProc(Message& m)
       at System.Windows.Forms.Button.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.

Reported by Flint.
I am thinking it has to do with an empty mail file or some.

**Comment by Deantwo** [comment]
Flint sent me all has mails, I am guessing they were from Uni4.
But as I expected, all the city mails were empty (0 bytes long).
I have no clue why this happen but I have made some changes to make sure it doesn't happen again.
